name: Build ODT and DOCX

on:
  workflow_dispatch:

jobs:
  build-odt:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc 3.7
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.7/pandoc-3.7-1-amd64.deb
          sudo dpkg -i pandoc-3.7-1-amd64.deb
          pandoc --version
    
      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3

      - name: Install pandoc-crossref
        run: |
          VERSION="0.3.20"
          URL="https://github.com/lierdakil/pandoc-crossref/releases/download/v$VERSION/pandoc-crossref-Linux-X64.tar.xz"

          echo "Downloading pandoc-crossref v$VERSION from $URL"
          curl -L "$URL" -o pandoc-crossref.tar.xz

          # Install xz-utils to extract tar.xz files
          sudo apt-get update
          sudo apt-get install -y xz-utils

          # Extract and install binary
          tar -xf pandoc-crossref.tar.xz
          sudo mv pandoc-crossref /usr/local/bin/
          pandoc-crossref --version

      - name: Create build directory
        run: mkdir -p build/odt

      - name: Generate ODT
        run: |
          pandoc \
            --from markdown\
            --resource-path="${PWD}/docs" \
            --toc -N \
            --listings \
            --filter pandoc-crossref \
            --lua-filter=pagebreak.lua \
            -o build/odt/teleseer_interoperability_output.odt \
            pandoc_metadata.yml \
            ${PWD}/docs/*.md
      
      - name: Generate DOCX
        run: |
          pandoc \
            --from markdown \
            --resource-path="${PWD}/docs" \
            --toc -N \
            --listings \
            --filter pandoc-crossref \
            --lua-filter=pagebreak.lua \
            # --reference-doc=template.docx \
            -o build/docx/teleseer_interoperability_output.docx \
            pandoc_metadata.yml \
            ${PWD}/docs/*.md
      
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: interoperability-report-odt
          path: build/odt/teleseer_interoperability_output.odt
