name: Build ODT

on:
  workflow_dispatch:

jobs:
  build-odt:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc lua5.3

      - name: Install pandoc-crossref
        run: |
          sudo apt-get install -y jq
          CROSSREF_URL=$(curl -s https://api.github.com/repos/lierdakil/pandoc-crossref/releases/latest \
            | jq -r '.assets[] | select(.name | test("Linux.*tar.gz$")) | .browser_download_url')
          echo "Downloading pandoc-crossref from $CROSSREF_URL"
          curl -L $CROSSREF_URL -o pandoc-crossref.tar.gz
          tar -xzf pandoc-crossref.tar.gz
          sudo mv pandoc-crossref /usr/local/bin/
          pandoc-crossref --version

      - name: Create build directory
        run: mkdir -p build/odt

      - name: Generate ODT
        run: |
          pandoc \
            --from markdown\
            --resource-path="${PWD}\docs" \
            --toc -N \
            --listings \
            --filter pandoc-crossref \
            --lua-filter=pagebreake.lua
            -o build\odt\teleseer_interoperability_output.odt \
            pandoc_metadata.yml \
            ${PWD}/docs/*.md

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: interoperability-report-odt
          path: build/odt/teleseer_interoperability_output.odt
