name: Build ODT

on:
  workflow_dispatch:

jobs:
  build-odt:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc pandoc-crossref lua5.3

      - name: Create build directory
        run: mkdir -p build/odt

      - name: Generate ODT
        run: |
          pandoc \
            --from markdown\
            --resource-path="${PWD}\docs" \
            --toc -N \
            --listings \
            --filter pandoc-crossref \
            --lua-filter=pagebreake.lua
            -o build\odt\teleseer_interoperability_output.odt \
            pandoc_metadata.yml \
            ${PWD}/docs/*.md

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: interoperability-report-odt
          path: build/odt/teleseer_interoperability_output.odt
