name: Build ODT

on:
  workflow_dispatch:

jobs:
  build-odt:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc lua5.3

      - name: Install pandoc-crossref
        run: |
          # Use a pinned version to ensure stability
          VERSION="0.3.17.0" # can update later if needed
          URL="https://github.com/jgm/pandoc/releases/download/3.7.0.2/pandoc-3.7.0.2-linux-amd64.tar.gz"

          echo "Downloading pandoc-crossref v$VERSION from $URL"
          curl -L "$URL" -o pandoc-crossref.zip
          sudo apt-get install -y unzip
          unzip pandoc-crossref.zip
          sudo mv pandoc-crossref /usr/local/bin/
          pandoc-crossref --version

      - name: Create build directory
        run: mkdir -p build/odt

      - name: Generate ODT
        run: |
          pandoc \
            --from markdown\
            --resource-path="${PWD}\docs" \
            --toc -N \
            --listings \
            --filter pandoc-crossref \
            --lua-filter=pagebreake.lua
            -o build\odt\teleseer_interoperability_output.odt \
            pandoc_metadata.yml \
            ${PWD}/docs/*.md

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: interoperability-report-odt
          path: build/odt/teleseer_interoperability_output.odt
